version: "3"

services:
  client:
    build:
      context: client
      args:
        REACT_APP_API_ADDRESS: "http://somnoynadno.ru:5000"
    container_name: vezdekod_web_client
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - server
    networks:
      - default

  server:
    build:
      context: server
    container_name: vezdekod_web_server
    ports:
      - 5000:5000
    restart: always
    networks:
      - default

networks:
  default:
